# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fb61a839f4ed32759b6140d48269eeed60984890ed8cfcb399c528728074c20fd3a6e0ddc3970deea434b4b6183b9364ba5be22fae3265832db5e8c6890006a

test:
  secret_key_base: 329d6758f8859bead9ef0c0e273536f099be274887f373fb47c51942526ad8574d348f369996a344a8c47c607c1e6db2b7b69e977fc06abc7fb19f08708a89aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
